....

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -33,16 +33,24 @@ jobs:
       run: cargo build --release
 
     - name: Run benchmarks
-      run: cargo bench --bench semaphore_benchmark -- --save-baseline new
+      run: cargo bench --bench semaphore_benchmark -- --save-baseline main
 
-    - name: List Benchmark Directory
-      run: ls -al target/criterion/semaphore_benchmark
+    - name: Debug - List contents of target directory
+      run: |
+        echo "Contents of target directory:"
+        ls -R target
+
+    - name: Debug - Find benchmark results
+      run: |
+        echo "Searching for benchmark results:"
+        find target -name "new" -type d
 
     - name: Upload benchmark results to GitHub Actions artifacts
       uses: actions/upload-artifact@v2
       with:
         name: benchmark-results
-        path: target/criterion/semaphore_benchmark/new
+        path: target/criterion
+        if-no-files-found: warn
 
     - name: Upload benchmark results to S3
       env:
@@ -50,4 +58,9 @@ jobs:
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       run: |
         BRANCH_NAME=$(echo ${GITHUB_REF} | sed 's/refs\/heads\///')
-        aws s3 cp target/criterion/semaphore_benchmark/new s3://switch-benchs/${BRANCH_NAME}/baseline.bench --region us-east-1
+        BENCHMARK_DIR=$(find target/criterion -name "new" -type d | head -n 1)
+        if [ -z "$BENCHMARK_DIR" ]; then
+          echo "Benchmark results directory not found"
+          exit 1
+        fi
+        aws s3 cp $BENCHMARK_DIR s3://switch-benchs/${BRANCH_NAME}/baseline.bench --recursive --region us-east-1
